version: '3.8'
services:
  db:
    container_name: neo4j
    image: neo4j:5.12
    ports:
      - '7474:7474'
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - data:/data
      - plugins:/plugins
    environment:
      - 'NEO4J_AUTH=${DB_USERNAME}/${DB_PASSWORD}'
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_PLUGINS=["apoc"]

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    links:
      - db

volumes:
  data: {}
  plugins: {}