CREATE
(m1:Machine { uuid: apoc.create.uuid(), type: 'TypeA', capacity: 10, status: 'IDLE' }),
(m2:Machine { uuid: apoc.create.uuid(), type: 'TypeA', capacity: 15, status: 'IDLE' }),
(m3:Machine { uuid: apoc.create.uuid(), type: 'TypeB', capacity: 20, status: 'IDLE' }),
(s1:Sweet { uuid: apoc.create.uuid(), name: 'banana split', price: 1, quantityInStock: 1, ingredients: ['BANANA', 'CHOCOLATE'] }),
(s2:Sweet { uuid: apoc.create.uuid(), name: 'weirdpear', price: 2, quantityInStock: 2, ingredients: ['APPLE'] }),
(s3:Sweet { uuid: apoc.create.uuid(), name: 'peak', price: 3, quantityInStock: 3, ingredients: ['CARAMEL', 'CHOCOLATE'] }),
(s4:Sweet { uuid: apoc.create.uuid(), name: 'nutella', price: 4, quantityInStock: 4, ingredients: ['CHOCOLATE', 'SUGAR', 'SUGAR', 'SUGAR', 'SUGAR'] }),
(m1)-[:PRODUCES]->(s1),
(m2)-[:PRODUCES]->(s2),
(m3)-[:PRODUCES]->(s2),
(m3)-[:PRODUCES]->(s3),
(m3)-[:PRODUCES]->(s4),
(o1:Order { uuid: apoc.create.uuid(), customer: 'Jean', status: 'PENDING' }),
(o2:Order { uuid: apoc.create.uuid(), customer: 'Ted', status: 'DELIVERED' }),
(o3:Order { uuid: apoc.create.uuid(), customer: 'Pierre', status: 'ACTIVE' }),
(o1)-[c1:CONTAINS { quantity: 1 }]->(s1),
(o1)-[c2:CONTAINS { quantity: 2 }]->(s2),
(o2)-[c3:CONTAINS { quantity: 3 }]->(s1),
(o3)-[c4:CONTAINS { quantity: 4 }]->(s3),

